src/providers/gpt-provider.js

https://wikia-inc.atlassian.net/browse/ADEN-7313

ADEN-7313 Add option changeCorrelator: false to GptProvider.flush().

---

examples/context.js
examples/slots/repeatable-slots/script.js
examples/style.css
spec/services/slot-injector.spec.js
spec/services/slot-repeater.spec.js
src/listeners/slot-listener.js
src/services/index.js
src/services/slot-injector.js
src/services/slot-repeater.js
src/utils/dimensions.js

Changes:
- extracted slot-injector, that injects slots to DOM avoiding viewport conflicts with others
- fixed slot-repeater so it looks for viewport space (not only position from top)

ADEN-7458 Add possibility to inject slot after another one is rendered

---

src/ad-products/styles/_uap.scss
src/ad-products/templates/uap/themes/hivi/hivi-bfaa.ts

Revert "ADEN-8518 Change UAP close button behaviour"

---

src/ad-products/styles/_uap.scss
src/ad-products/templates/uap/themes/hivi/hivi-bfaa.ts
src/ad-products/templates/uap/themes/hivi/hivi-theme.ts

Remove unstick button from UAP on unstick.

ADEN-8518 Do not hide BFAA when unstick is clicked.

---

examples/context.ts
spec/ad-bidders/prebid/index.spec.ts
spec/ad-bidders/prebid/prebid-settings.spec.ts
src/ad-bidders/prebid/index.ts
src/ad-bidders/prebid/prebid-settings.ts

- handle all prebid key-vals manually
- removed `bidders.prebid.useBuiltInTargetingLogic` configuration

ADEN-8580 Remove built in logic and grab hb_deal_* manually

---

spec/ad-engine/listeners/scroll-listener.spec.ts
src/ad-engine/ad-engine.ts
src/ad-engine/listeners/scroll-listener.ts

Add async "ready" property to Ads module.

ADEN-8686 Change interface of scrollListener.addSlot.

---

src/ad-engine/listeners/slot-listener.ts
src/ad-products/templates/sticky-tlb.ts

How promise rejection is handled: https://stackblitz.com/edit/promise-rejection

ADEN-8586 Improve HiVi TLB UX on slow connection

---

examples/context.ts
spec/ad-bidders/a9/a9.spec.ts
src/ad-bidders/a9/index.ts

This reverts commit be7d66d7af48094cf752b799b9a353fc590c4e09.

ADEN-8666 | Revert removing slotId from a9 context (#397)

---

src/ad-products/templates/sticky-ad.ts
src/ad-products/templates/uap/themes/hivi/hivi-bfaa.ts
src/ad-products/templates/uap/themes/hivi/stickiness.ts

Changelog:
* changed stickiness const `SLOT_UNSTICK_IMMEDIATELY` to `SLOT_FORCE_UNSTICK`

ADEN-8938 Fix BFAA force-unstick event

---

@types/apstag/index.d.ts
@types/cmp/index.d.ts
@types/window/index.d.ts
README.md
package.json
src/ad-bidders/a9/index.ts
src/ad-bidders/base-bidder.ts
src/ad-bidders/index.ts
src/ad-bidders/prebid/index.ts
src/ad-bidders/prebid/prebid-helper.ts
src/ad-bidders/prebid/price-helper.ts
src/ad-bidders/wrappers/apstag.ts
src/ad-engine/utils/flow-control.ts
src/ad-products/templates/sticky-base.ts
src/ad-products/templates/uap/themes/hivi/stickiness.ts
src/ad-services/bill-the-lizard/index.ts

ADEN-8979 Add waitForViewed to Stickiness.

---

examples/big-fancy-ad-above-config.ts
examples/templates/abcd/script.ts
examples/templates/hivi-uap-ab/script.ts
examples/templates/hivi-uap-ctp/script.ts
examples/templates/hivi-uap-static/script.ts
examples/templates/hivi-uap-stickiness-not-allowed/script.ts
examples/templates/hivi-uap-sticky-bfab/script.ts
examples/templates/hivi-uap/script.ts
examples/templates/vuap/script.ts
src/ad-products/templates/uap/big-fancy-ad-above.ts

Follow up for https://github.com/Wikia/ad-engine/pull/428

ADEN-8986 Fix BFAA navbar position

---

package-lock.json
package.json
tests/common/ad-slots.js
tests/common/network.js
tests/specs/slots/viewport-conflict-ad.desktop.test.js

Network downgraded

---

spec/ad-products/templates/uap/themes/hivi/hivi.spec.ts
src/ad-products/templates/uap/themes/hivi/hivi-bfaa.ts
src/ad-products/templates/uap/themes/hivi/hivi-bfab.ts
src/ad-products/templates/uap/themes/hivi/hivi-theme.ts
src/ad-products/templates/uap/universal-ad-package.ts

This reverts commit af383a3f8c282771dd73d1cfd92d51597b3b9cd4.

Revert "ADEN-9532 Set correct image on UAP startup. (#584)"

---

platforms/ucp/setup/context/targeting/ucp-targeting.setup.ts

Backend is ready: 
https://github.com/Wikia/unified-platform/blob/master/extensions/fandom/AdEngine/AdEngine.class.php#L127-L128

ADEN Add missing s0v and s0c

---

platforms/ucp/templates/handlers/bfaa-video-handler.ts
platforms/ucp/templates/handlers/bfab-video-handler.ts
platforms/ucp/templates/helpers/video-helper.ts

Signed-off-by: Jacek Bronski-Jankowski <jjankowski@wikia-inc.com>

ADEN-9924 Set ctp, audio and slotNameSuffix.

---

platforms/ucp/styles.scss

ADEN-10029 Fix dark theme on UAP HiVi.

---

platforms/shared/consent/tracking-opt-in-wrapper.ts
src/ad-engine/services/tracking-opt-in.ts

Bump @wikia/tracking-opt-in to v3.0.3.

ADEN-10054 Bump @wikia/tracking-opt-in to v3.0.3.

---

src/ad-products/tracking/video/video-event-data-provider.ts
src/ad-products/video/jwplayer/helpers/jwplayer-tracking-helper.ts
src/ad-products/video/player/porvata/porvata-listener.ts

Revert "Revert "ADEN-10174 Adding player ad info cache in case of video error…"

---

platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-slots-definition-repository.ts

This reverts commit 7a7fac9c79e88a6bc7ad87e06e62f565ef57507f.

ADEN-10924 Revert quick fix for top_leaderboard appearing on FV page

---

platforms/ucp-mobile/ad-context.ts

Let's revert it and see if it has a positive impact on VCR.
This reverts commit a9a824185fa05963d4c68079d195e8179bf444d0.

ADEN-11172 Revert Changing video ad units for ucp_mobile platform

---

platforms/ucp-desktop/ad-context.ts
src/ad-engine/services/bab-detection.ts

Ticket: https://wikia-inc.atlassian.net/browse/ADEN-11174

ADEN-11174 Fix ads placeholders + Blockthrough

---

platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-dynamic-slots.setup.ts

Ticket: https://wikia-inc.atlassian.net/browse/ADEN-10898

ADEN-10898 Allowing StickyTLB template on special pages

---

platforms/shared/utils/collapsed-messages/newsletter-form-box.ts

https://fandom.atlassian.net/browse/ADEN-11604

ADEN-11604 Add event for Newsletter Form submission

---

platforms/ucp-desktop/styles.scss

This reverts commit 58e0701dbe3ff2e8550ebc1e839acb46c07ceb94.

ADEN-11737 Revert fix for hidden local nav

---

platforms/shared/tracking/tracking.setup.ts
src/ad-services/optimera/index.ts
src/communication/event-types.ts

https://fandom.atlassian.net/browse/ADEN-11827

ADEN-11827 Fix tracking for Optimera

---

platforms/shared/context/targeting/targeting-strategies/interfaces/page-level-tags.ts
platforms/shared/context/targeting/targeting-strategies/strategies/page-context-strategy.ts

https://fandom.atlassian.net/browse/ADEN-12028

ADEN-12028 Add '_p' prefix to page level tags

---

spec/ad-tracking/slot-tracking-middleware.spec.ts
src/ad-tracking/slot-tracking-middleware.ts

https://fandom.atlassian.net/browse/ADEN-12069

ADEN-12069 Track PPID to adengadinfo table

---

platforms/shared/tracking/tracking.setup.ts
src/ad-services/audigent/index.ts

https://fandom.atlassian.net/browse/ADEN-12114

ADEN-12114 Remove Audigent from key-vals tracking

---

platforms/f2/modes/f2-ads-mode-deprecated.service.ts
platforms/f2/modes/f2-ads-mode.service.ts

https://fandom.atlassian.net/browse/ADEN-12180

ADEN-12180 Extend FIG to N&S

---

platforms/shared/context/targeting/targeting-strategies/strategies/combined-strategy.ts
platforms/shared/context/targeting/targeting-strategies/strategies/legacy-strategy.ts
platforms/shared/context/targeting/targeting-strategies/strategies/page-context-strategy.ts

[Ticket](https://fandom.atlassian.net/browse/ADEN-12204)

ADEN-12204 - Remove setting ESRB based on directedAtChildren flags 

---

@types/live-connect/index.d.ts
platforms/f2/modes/f2-ads-mode-deprecated.service.ts
platforms/f2/modes/f2-ads-mode.service.ts
platforms/shared/setup/base-context.setup.ts
spec/ad-services/live-connect/live-connect.spec.ts
src/ad-services/live-connect/index.ts

https://fandom.atlassian.net/browse/ADEN-12189

ADEN-12189 Integrate LiveConnect into f2

---

platforms/shared/setup/player.setup.ts

[Ticket](https://fandom.atlassian.net/browse/ADEN-12235)

ADEN-12235 - Quick fix for JWPlayer in F2

---

@types/live-connect/index.d.ts
platforms/f2/modes/f2-ads-mode-deprecated.service.ts
platforms/f2/modes/f2-ads-mode.service.ts
platforms/shared/setup/base-context.setup.ts
spec/ad-services/live-connect/live-connect.spec.ts
src/ad-engine/services/local-cache.ts
src/ad-engine/services/universal-storage.ts
src/ad-products/templates/uap/resolved-state-switch.ts
src/ad-services/live-connect/index.ts

https://fandom.atlassian.net/browse/ADEN-12189

ADEN-12189 Add LI to N&S

---

src/ad-services/ias-publisher-optimization/index.ts
src/platforms/f2/modes/f2-ads-mode.service.ts
src/platforms/shared/setup/gpt.setup.ts
src/platforms/sports/modes/ads/sports-ads.mode.ts
src/platforms/ucp-desktop/modes/ucp-desktop-ads-mode.service.ts
src/platforms/ucp-desktop/modes/ucp-desktop-lighter-ads-mode.service.ts
src/platforms/ucp-mobile/modes/ucp-mobile-ads-mode.service.ts
src/platforms/ucp-mobile/modes/ucp-mobile-lighter-ads-mode.service.ts

[Ticket](https://fandom.atlassian.net/browse/ADEN-12308)

ADEN-12308 - Removed unnecessary waiting for GPT from IAS 

---

src/ad-services/eyeota/index.ts
src/communication/event-types.ts
src/platforms/shared/tracking/load-times-tracker.ts
src/platforms/ucp-mobile/ucp-mobile-legacy-setup.ts

[Ticket](https://fandom.atlassian.net/browse/ADEN-12273)

ADEN-12273 - Added reporting failed pixel loading in Eyeota

---

spec/ad-products/video/jwplayer/helpers/jwplayer-helper-skipping-sponsored-video.spec.ts
src/ad-products/video/jwplayer/helpers/jwplayer-helper-skipping-sponsored-video.ts

This reverts commit 9c7275cc8a2ff3861abc9693bd7d2a544563542c.
We'll merge it again with 1-2 more changes from [ADEN-12452](https://github.com/Wikia/ad-engine/tree/ADEN-12452) branch.

Revert "ADEN-12460 Fix blocking preroll for the first video (#1614)"

---

src/ad-products/video/jwplayer/helpers/jwplayer-helper.ts
src/platforms/ucp-desktop/ad-context.ts
src/platforms/ucp-mobile/ad-context.ts

https://fandom.atlassian.net/browse/ADEN-12430

Aden 12430

---

src/ad-bidders/prebid/index.ts
src/ad-bidders/prebid/price-helper.ts
src/platforms/ucp-desktop/bidders/prebid/pubmatic.ts

Revert "ADEN-12349 Prebid Module initial cleanup"

---

spec/ad-products/video/jwplayer/helpers/jwplayer-helper-skipping-sponsored-video.spec.ts
src/ad-products/video/jwplayer/handlers/jwplayer-handler.ts
src/ad-products/video/jwplayer/helpers/jwplayer-helper-skipping-sponsored-video.ts

Move sponsoredVideos from global to class property and ensure its set earlier

ADEN-12452 Improve 1st video preroll behaviour

---

src/ad-bidders/prebid/index.ts
src/ad-bidders/prebid/price-helper.ts
src/platforms/ucp-desktop/bidders/prebid/pubmatic.ts

Revert "Revert "ADEN-12349 Prebid Module initial cleanup (#1606)" (#1626)"
This reverts commit d37f3a62a334b2843e66030aa17cfe3de24afd06.

ADEN-12349 Revert-revert

---

src/platforms/giantbomb/ad-context.ts
src/platforms/giantbomb/giantbomb-platform.ts

https://fandom.atlassian.net/browse/ADEN-12490

ADEN-12490 Create TargetingSetup on Giantbomb

---

src/platforms/comicvine/ad-context.ts
src/platforms/comicvine/comicvine-platform.ts

https://fandom.atlassian.net/browse/ADEN-12492

ADEN-12492 Create TargetingSetup on Comicvine

---

src/ad-services/live-connect/index.ts
src/communication/event-types.ts
src/platforms/shared/tracking/load-times-tracker.ts

Added an additional event to track situations when LiveConnect data is cached

ADEN-12529 - New LiveConnect event

---

src/platforms/comicvine/setup/dynamic-slots/comicvine-dynamic-slots.setup.ts
src/platforms/gamefaqs/setup/dynamic-slots/gamefaqs-dynamic-slots.setup.ts
src/platforms/gamespot/setup/dynamic-slots/gamespot-dynamic-slots.setup.ts
src/platforms/giantbomb/setup/dynamic-slots/giantbomb-dynamic-slots.setup.ts
src/platforms/metacritic/setup/dynamic-slots/metacritic-dynamic-slots.setup.ts

https://fandom.atlassian.net/browse/ADEN-12545

ADEN-12545 Ad slots go into wrong placeholders

---

spec/platforms/news-and-ratings/shared/context/targeting/news-and-ratings-targeting.setup.spec.ts
src/platforms/shared-news-and-ratings/context/targeting/news-and-ratings-targeting.setup.ts

https://fandom.atlassian.net/browse/ADEN-12534

ADEN-12534 Fix the JSON.parse(string_cookie) issue

---

spec/platforms/news-and-ratings/metacritic/setup/context/targeting/metacritic-targeting.setup.spec.ts
src/platforms/news-and-ratings/comicvine/comicvine-platform.ts
src/platforms/news-and-ratings/comicvine/setup/context/targeting/comicvine-targeting.setup.ts
src/platforms/news-and-ratings/gamefaqs/gamefaqs-platform.ts
src/platforms/news-and-ratings/gamefaqs/setup/context/targeting/gamefaqs-targeting.setup.ts
src/platforms/news-and-ratings/gamespot/gamespot-platform.ts
src/platforms/news-and-ratings/gamespot/setup/context/targeting/gamespot-targeting.setup.ts
src/platforms/news-and-ratings/giantbomb/giantbomb-platform.ts
src/platforms/news-and-ratings/giantbomb/setup/context/targeting/giantbomb-targeting.setup.ts
src/platforms/news-and-ratings/metacritic/metacritic-platform.ts
src/platforms/news-and-ratings/metacritic/setup/context/targeting/metacritic-targeting.setup.ts
src/platforms/news-and-ratings/tvguide/setup/context/targeting/tvguide-targeting.setup.ts
src/platforms/news-and-ratings/tvguide/tvguide-platform.ts

https://fandom.atlassian.net/browse/ADEN-12512
[ADEN-12512]: https://fandom.atlassian.net/browse/ADEN-12512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ADEN-12512 - Add vertical key values to N&R sites

---

src/platforms/news-and-ratings/shared/setup/context/targeting/news-and-ratings-targeting.setup.ts

https://fandom.atlassian.net/browse/ADEN-12666

ADEN-12666 Add default value to 'ftag' and 'ttag' targeting keys

---

src/platforms/news-and-ratings/metacritic/ad-context.ts
src/platforms/news-and-ratings/metacritic/metacritic-platform.ts
src/platforms/news-and-ratings/tvguide/ad-context.ts
src/platforms/news-and-ratings/tvguide/tvguide-platform.ts

https://fandom.atlassian.net/browse/ADEN-12675

ADEN-12675 Add NewsAndRatingsTargetingSetup to Metacritic

---

spec/platforms/news-and-ratings/shared/context/targeting/news-and-ratings-targeting.setup.spec.ts
src/platforms/news-and-ratings/shared/setup/context/targeting/news-and-ratings-targeting.setup.ts

https://fandom.atlassian.net/browse/ADEN-12721

ADEN-12721 Decode adtags on N&R platforms

---

src/ad-services/audigent/index.ts
src/platforms/news-and-ratings/shared/modes/news-and-ratings-ads-mode.ts

https://fandom.atlassian.net/browse/ADEN-12719

ADEN-12719 Add Audigent to N&R platforms

---

spec/platforms/news-and-ratings/metacritic/setup/context/targeting/metacritic-targeting.setup.spec.ts
src/platforms/news-and-ratings/metacritic/setup/context/targeting/metacritic-targeting.setup.ts

https://fandom.atlassian.net/browse/ADEN-12749

ADEN-12749 Add "ptype" key val to Metacritic platform

---

spec/ad-bidders/a9/a9.spec.ts
src/ad-bidders/a9/index.ts
src/ad-bidders/index.ts
src/platforms/shared/bidders/bidders-state.setup.ts

[Ticket](https://fandom.atlassian.net/browse/ADEN-12704)

ADEN-12704 - Added checking matching COPPA to A9

---

src/ad-services/captify/index.ts
src/platforms/news-and-ratings/shared/setup/context/base/news-and-ratings-base-context.setup.ts

https://fandom.atlassian.net/browse/ADEN-12802

ADEN-12802 Change captify ID for N&R sites

---

src/core/utils/wait-for.ts
src/platforms/news-and-ratings/tvguide/setup/dynamic-slots/tvguide-dynamic-slots.setup.ts

https://fandom.atlassian.net/browse/ADEN-12847

ADEN-12847 Fix dynamic slots logic on SPA TVGuide

---

src/platforms/shared/setup/tracking-parameters.setup.ts

Revert "ADEN-12836 - Modified pvUniqueId source on N&R"

---

src/platforms/shared/setup/tracking-parameters.setup.ts

Revert "Revert "ADEN-12836 - Modified pvUniqueId source on N&R""

---

src/platforms/news-and-ratings/gamefaqs/bidders/rubicon.ts
src/platforms/news-and-ratings/gamefaqs/setup/context/prebid/gamefaqs-prebid-config.setup.ts
src/platforms/news-and-ratings/gamespot/bidders/rubicon.ts
src/platforms/news-and-ratings/gamespot/setup/context/prebid/gamespot-prebid-config.setup.ts
src/platforms/news-and-ratings/giantbomb/bidders/rubicon.ts
src/platforms/news-and-ratings/giantbomb/setup/context/prebid/giantbomb-prebid-config.setup.ts
src/platforms/news-and-ratings/metacritic/bidders/rubicon.ts
src/platforms/news-and-ratings/metacritic/setup/context/prebid/metacritic-prebid-config.setup.ts
src/platforms/news-and-ratings/tvguide/bidders/rubicon.ts
src/platforms/news-and-ratings/tvguide/setup/context/prebid/tvguide-prebid-config-setup.service.ts

https://fandom.atlassian.net/browse/ADEN-12877
ADEN-12877 | Add Rubicon (Magnite) prebid video on N&R
affected sites: metacritic, gamefaqs, gamespot, giantbomb & tvguide

ADEN-12877 | Add Rubicon prebid video on N&R

---

webpack.platforms.js

Required by #1916 (this changes must be present on "dev" branch before #1916 can be merge)

Bundle size report prequisite

---

spec/platforms/shared/bidders/bidders-state.setup.spec.ts
src/platforms/shared/bidders/bidders-state.setup.ts

https://fandom.atlassian.net/browse/ADEN-13101
Disable not COPPA compliant bidders (kargo, verizon) on kid wikis

ADEN-13101 Disable not COPPA compliant bidders on kid wikis

---

spec/platforms/news-and-ratings/shared/setup/dynamic-slots/news-and-ratings-anyclip.setup.spec.ts
src/ad-services/anyclip/index.ts
src/platforms/news-and-ratings/shared/setup/dynamic-slots/news-and-ratings-anyclip.setup.ts
src/platforms/news-and-ratings/shared/setup/dynamic-slots/news-and-ratings-dynamic-slots-neutron.setup.ts
src/platforms/shared/tracking/data-warehouse.ts

Revert "VIDEO-524 Inject Anyclip in-content player on the TV Guide listing page"

---

src/platforms/news-and-ratings/comicvine/ad-context.ts
src/platforms/news-and-ratings/gamefaqs/ad-context.ts

We want different from TVG Anyclip player on ComicVine and GameFAQs.

COTECH-648 fix ComicVine and GameFAQs players

---

src/ad-bidders/prebid/index.ts

https://fandom.atlassian.net/browse/ADEN-13307

ADEN-13307 | Update PriceGranularity

---

src/platforms/shared/setup/base-context.setup.ts

https://fandom.atlassian.net/browse/ADEN-13175
Remove all flags connected to AgeGate

ADEN-13175 Remove legacy AgeGate flag

---

spec/core/services/session-cookie.spec.ts
src/core/services/session-cookie.ts

The mechanism was working great, but we were reading from one key and saving data under other key...

TACO-118 Fix reading from basset cookie

---

src/platforms/ucp-desktop/templates/handlers/bfaa/bfaa-ucp-desktop-config-handler.ts

AC:
- Gallery leaderboard slot will be loaded with UAPs

ADEN-13459 Add gallery leaderboard slot to list of eligible slots with UAP

---

src/ad-bidders/prebid/ats/ats.ts

Fixes ATS misconfiguration that was spotted by LiveRamp team.

TACO-120 ATS misconfiguration

---

src/platforms/ucp-mobile/styles.scss

https://fandom.atlassian.net/browse/ADEN-13636
Added small margin after anyclip player

[ADEN-13636] Added margin after #incontent_player (anyclip) video

---

spec/ad-services/double-verify/double-verify.spec.ts
src/ad-services/double-verify/index.ts

Revert "ADEN-13625: Fix DoubleVerify calls not including ad unit paths"

---

src/platforms/news-and-ratings/gamefaqs/setup/context/slots/gamefaqs-anyclip.setup.ts
src/platforms/news-and-ratings/gamefaqs/styles.scss

Revert "COTECH-765 | Enable anyclip on mobile on GameFAQs"

---

src/platforms/news-and-ratings/gamefaqs/setup/context/slots/gamefaqs-anyclip.setup.ts

We can merge and deploy it after this GameFAQs changes are deployed: https://github.com/Wikia/gamefaqs/pull/135

COTECH-765 | GameFAQs anyclip cleanup

---

spec/ad-services/anyclip/anyclip.spec.ts
src/ad-services/anyclip/anyclip-tracker.ts
src/ad-services/anyclip/index.ts

Revert "COTECH-808 | track eligible for anyclip"

---

src/ad-products/video/jwplayer/helpers/vast-tagless-request.ts

Since slotService.add(adSlot) is firing a bidder parameters update further in the pipeline, there is no guarantee that even if bidders finished that slot targeting is updated before we create a VAST url.
Instead of rebuilding the whole pipeline I read those directly from bidders

COTECH-832 | enforce bidder params

---

README.md

Add useful information to README

Update README.md with adengine_version=local

---

spec/platforms/shared/setup/player.setup.spec.ts
src/platforms/shared/setup/player.setup.ts

[COTECH-975](https://fandom.atlassian.net/browse/COTECH-975) @Wikia/cotech 
[COTECH-975]: https://fandom.atlassian.net/browse/COTECH-975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

COTECH-975 Correct false positive test results in PlayerSetup

---

src/ad-services/anyclip/index.ts
src/ad-services/connatix/index.ts
src/core/video/index.ts
src/core/video/no-incontent-player-experiment.ts
src/platforms/shared/setup/base-context.setup.ts

https://fandom.atlassian.net/browse/COTECH-997

COTECH-997 | No in-content player experiment

---

spec/platforms/shared/setup/jwp-strategy-rules.setup.spec.ts
spec/platforms/shared/setup/player.setup.spec.ts
src/platforms/shared/setup/jwp-strategy-rules.setup.ts
src/platforms/shared/setup/player.setup.ts

https://fandom.atlassian.net/browse/COTECH-1062

COTECH-1062 | use icFeaturedVideoPlayer for connatix and JWP strategy-rules

---

package.json
webpack.platforms.js

Fixes `npm run bundle-analyzer` command that is currently not working.

Fix webpack bundle analyzer

---

spec/ad-bidders/prebid/id5/id5.spec.ts
src/ad-bidders/prebid/id5/id5.ts

Revert "TACO-447 Save ID5 AB testing control group to local storage"

---

src/ad-services/identity-setup/index.ts

https://fandom.atlassian.net/browse/TACO-422
Pass PV Unique ID as GAM key-val

TACO-422 Pass PageView Unique ID as GAM key-val

---

spec/ad-bidders/a9/a9.spec.ts

Revert "Update a9.spec.ts"

---

package.json

Manually bump version to 146.13.5

TACO-427 Manually bump version to 146.13.5

---

.github/labeler.yml
.github/pr-labeler.yml
.github/workflows/pr-labeler.yml

Switch to official Github [action/labeler](https://github.com/actions/labeler)

Change default label to minor to stop releasing features as patch changes

---

src/core/providers/gpt-provider.ts

https://fandom.atlassian.net/browse/COTECH-1134

COTECH-1134 | add null checks for adSlot in gpt events

---

spec/ad-bidders/prebid/utils/id-retriever.spec.ts
src/ad-bidders/prebid/utils/id-retriever.ts

In this PR I've added a new value to BOI string.

TACO-486 - Added pubcid.org ID to BOI

---

src/platforms/shared/templates/helpers/uap-dom-manager.ts

ADEN-13939 - resize TLB placeholders on refresh #2414

---

src/platforms/ucp-desktop/styles.scss

Ticket: https://fandom.atlassian.net/browse/ADEN-13869
Note: Testing instructions are in the ticket

ADEN-13869: Update floor adhesion background color
