Wikia/ad-engine

- src/ad-engine/video/player/porvata/ima/google-ima-setup.js
Use adSlot.getSlotName() instead of slotName which can be two pos params
> ADEN-7773 Fix ad unit in UAP

- spec/ad-engine/models/ad-slot.spec.ts
- src/ad-engine/models/ad-slot.ts
If slot has no element, then it returns -1.
> ADEN-8842 AdSlot getTopOffset handles no slot element.

- package.json
- spec/tslint.json
- src/ad-bidders/index.ts
- src/ad-bidders/wrappers/apstag.ts
- src/ad-engine/listeners/slot-listener.ts
- src/ad-engine/utils/geo.ts
- src/ad-engine/utils/not-implemented-exception.ts
- tsconfig.json
Run type check for ad-engine and ad-bidders on commit.
I removed obsolete "no-unused-locals" setting from tslint config.
I added check of types (in ad-engine and ad-bidders) on commit to ensure that we do not introduce new errors there.
> ADEN-9031 Add no-unused-variable rule as error.

- platforms/shared/context/targeting/ucp-targeting.setup.ts
In Oasis we have this logic at the phase when we set up the ad context in JS: https://github.com/Wikia/app/blob/6f029810527f757dea0b6d678f933542d59ff8bb/extensions/wikia/AdEngine3/src/setup.js#L76
Docs: https://wikia-inc.atlassian.net/wiki/spaces/ADEN/pages/1009549793/External+test+and+showcase
Linked PR: https://github.com/Wikia/unified-platform/pull/2516
> ADEN-10326 Set correct src for test environments with testSrc set

- platforms/gamepedia/styles.scss
The `body.hide-ads` class is used to hide advertisements for all Hydra skins when the user has the appropriate entitlement.
https://wikia-inc.atlassian.net/browse/GPUCP-471
> GPUCP-471 | Fix hiding advertisements for all Hydra skins.

- platforms/ucp-mobile/ad-context.ts
- platforms/ucp-no-ads/setup/wiki-context.setup.ts
- platforms/ucp/ad-context.ts
Currently, ad-engine uses services.wikia.com domain to call bill-the-lizard and ICBM endpoints, which necessitates another network connection and TLS handshake. Let's use services.fandom.com domain instead, which is already being used by other UCP FE clients.
> [UCP] Use services.fandom.com for bill-the-lizard and ICBM

- platforms/ucp-desktop/setup/state/slots/ucp-desktop-slots-state-setup.ts
It's a P2 fix before we get with FandomDesktop on a bigger scale. There is room for improvement since now the same code is in at least two places. On the other hand, it may make sense from the business point of view if we don't want to have the player enabled on other platforms.
> ADEN-11118 Distroscale changes on FandomDesktop

- spec/ad-services/permutive/permutive.spec.ts
- src/ad-services/permutive/index.ts
This is a quick-fix for regression we introduced while working on src=uap. More info in the ticket: [ADEN-11424](https://fandom.atlassian.net/browse/ADEN-11424)
> ADEN-11424 Fix regression for Permutive

- .eslintrc.json
- platforms/.eslintrc.json
- spec/.eslintrc.json
- spec/ad-engine/ad-slot-fake.ts
- spec/ad-engine/listeners/porvata-listener.spec.ts
- spec/ad-engine/listeners/scroll-listener.spec.ts
- spec/ad-engine/runner/runner.spec.ts
- spec/ad-engine/services/context-service.spec.ts
- spec/ad-engine/services/slot-injector.spec.ts
- spec/ad-engine/services/slot-service.spec.ts
- spec/ad-engine/utils/dimensions.spec.ts
- spec/ad-engine/utils/targeting.spec.ts
- spec/ad-engine/utils/try-property.spec.ts
- spec/ad-products/templates/uap/resolved-state.spec.ts
- spec/ad-products/video/porvata4/native-fullscreen.spec.ts
- spec/ad-products/video/porvata4/plugins/ias/ias-video-tracker.spec.ts
- spec/platforms/shared/utils/collapsed-messages/message-box-service.spec.ts
- spec/platforms/shared/utils/placeholder-service-helper.spec.ts
- src/.eslintrc.json
- src/ad-bidders/.eslintrc.json
- src/ad-engine/.eslintrc.json
- src/ad-engine/services/local-cache.ts
- src/ad-engine/services/session-cookie.ts
- src/ad-engine/utils/targeting.ts
- src/ad-products/.eslintrc.json
- src/ad-services/.eslintrc.json
- src/ad-services/ias-publisher-optimization/index.ts
- src/ad-tracking/.eslintrc.json
- src/platforms-shared/.eslintrc.json
Basically it's bringing back the blacklisted imports removed with `tslint` in this commit: https://github.com/Wikia/ad-engine/pull/1223/commits/f12ca36114605d5383b5622e14a28011322c93a5
> ADEN-11503 Bring back blacklisted imports

- package-lock.json
- package.json
`ts-node` was added in [ADEN-8364](https://fandom.atlassian.net/browse/ADEN-8364) as part of WDIO tests, which are now in a separate repo, so we don't need it anymore.
> remove ts-node

- platforms/shared/setup/base-context.setup.ts
- platforms/shared/slots/slots-context.ts
- platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
- spec/platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.spec.ts
We've enabled globally a new behaviour of `floor_adhesion` slot on featured video pages on Friday, 9/9. The numbers are looking good, so we can remove the variable from the instant-config service and its usages in the AdEngine.
> ADEN-12174 Remove an instant-config variable we do not need anymore

- platforms/shared/setup/base-context.setup.ts
- spec/ad-products/video/jwplayer/helpers/jwplayer-helper.spec.ts
- spec/ad-products/video/jwplayer/streams/jwplayer-stream-state.spec.ts
- src/ad-engine/listeners/listeners.ts
- src/ad-products/tracking/video/video-event-data-provider.ts
- src/ad-products/video/jwplayer/handlers/jwplayer-tracking-handler.ts
- src/ad-products/video/jwplayer/helpers/jwplayer-helper.ts
- src/ad-products/video/jwplayer/streams/jwplayer-stream-state.ts
The code changes introduce more requests for video ads for 3rd, 4th and so on video plays. We block requesting ads for the 2nd video because it may be a sponsored one.
> ADEN-12209 Change the video ads logic

- spec/core/utils/targeting.spec.ts
- src/core/utils/targeting.ts
We will upload bundles as TAGS into tag manager and they are set up in lower case there, whereas in ICBM we use upper case ones. For GAM it does not matter
> ADEN-12171 | case insensitive VIDEO_TIER_3 bundle recognition

- spec/ad-products/video/jwplayer/helpers/jwplayer-helper-skipping-sponsored-video.spec.ts
- src/ad-products/video/jwplayer/handlers/jwplayer-handler.ts
- src/ad-products/video/jwplayer/helpers/jwplayer-helper-skipping-sponsored-video.ts
- src/ad-products/video/jwplayer/helpers/jwplayer-helper.ts
- src/core/utils/script-loader.ts
Moving `sponsoredVideos` from global to class property and ensure its set earlier doesn't help minimise the errors logged to Kibana. This is a 2nd quick-fix that forces the fallback API call to be synchronous.
> ADEN-12452 Improve 1st video preroll behaviour 

- spec/platforms/shared/context/targeting/targeting-strategies/providers/open-rtb2-tags.spec.ts
- src/ad-bidders/a9/index.ts
- src/ad-bidders/a9/types.ts
- src/platforms/shared/context/targeting/targeting-strategies/factories/create-open-rtb2-context.ts
- src/platforms/shared/context/targeting/targeting-strategies/models/fandom-context.ts
- src/platforms/shared/context/targeting/targeting-strategies/models/open-rtb2.ts
- src/platforms/shared/context/targeting/targeting-strategies/providers/open-rtb2-tags.ts
- src/platforms/shared/context/targeting/ucp-targeting.setup.ts
- src/platforms/shared/index.ts
This PR implements OpenRTB API 2.5 specification and to do so it uses the data gathered from `FandomContext`. The created OpenRTB object is then used by Amazon A9 via `apstag.init` method. Amazon only implemented OpenRTB's `user` and `site` objects and we can only provide `site` data at the moment (maybe we will provide some user data in the future).
> ADEN-12898 Extend current A9 initialization

- spec/platforms/shared/context/targeting/targeting-strategies/providers/open-rtb2-tags.spec.ts
- src/platforms/shared/context/targeting/targeting-strategies/models/fandom-context.ts
- src/platforms/shared/context/targeting/targeting-strategies/providers/open-rtb2-tags.ts
Apparently `window.fandomContext.site.tags` can be either object or null... What a pity that TypeScript typings do not reflect that at all.
This is a quick fix to OpenRtb2Tags so it handles a situation when `window.fandomContext.site.tags` is set to null.
I will go and fix `FandomContext` typings in separate PR so they are in line with the reality. We have TypeScript so let's use it to our advantage, not the other way around.
> ADEN-13053 Fix TypeError in OpenRtb2Tags

- spec/platforms/shared/setup/metric-reporter.setup.spec.ts
- src/platforms/shared/setup/metric-reporter.setup.ts
- src/platforms/shared/tracking/metric-reporter.ts
https://fandom.atlassian.net/browse/ADEN-13294
[icMonitorTrafficThreshold](https://services.fandom.com/icbm/dashboard/feature_flag/icMonitorTrafficThreshold) is a great variable, but for now it had a very simple format (integer). While implementing some of the reporting logic in IdentityEngine, I wanted to use the same ICBM variable to control sampling, but I would like to manage percentages and geos in Identity monitoring independent of AdEngine monitoring settings. That's why the ICBM variable will be moving from integer to JSON object with more complex format.
This PR provides a backward compatible implementation to AdEngine, so it will be able to handle icMonitorTrafficThreshold being both integer and JSON object.
> ADEN-13294 Handle icMonitorTrafficThreshold being JSON object

- src/platforms/shared/tracking/tracking.setup.ts
In recent migration revert, we missed one file. It was found when we ( me and @JackThePie ) were analysing what is going on with our HEMs. 
https://github.com/Wikia/ad-engine/commit/5f1d31eb8c72ca5cc29e00b3c4cb2f1330b16d4a#diff-93a8db8182c3455559133794f9780d2c72dc6ca8b279568e4d10a105beb12aba
vs 
https://github.com/Wikia/ad-engine/commit/1a68cf679cf5431a049316965e98d154d749ffbf
Showing 24 changed files with 10 additions and 1,047 deletions.
vs
Showing 23 changed files with 1,030 additions and 10 deletions.
we can clearly see that one file was not reverted. In this PR I've fixed that.
> ADEN-13299 - Fixed tracking Identity

- spec/ad-bidders/prebid/intent-iq/intent-iq.spec.ts
- src/ad-bidders/prebid/index.ts
- src/ad-bidders/prebid/intent-iq/intent-iq.ts
- src/ad-tracking/slot-tracker.ts
https://fandom.atlassian.net/browse/ADEN-13281
https://fandom.atlassian.net/browse/ADEN-13300
We are trying to find best possible way to send IntentIQ report data in a consistent manner, so the data from GAM reports is more or less the same. After previous fixes (introduced by #1975) data from both sources got very close, but still not close enough.
This is yet another, and probably the best way to send report to IntentIQ only when prebid ad is rendered to the end user. It uses `adRenderSucceeded` [1] event, which seems to be the best source of truth that we can get for such a case.
<hr>
[[1] Prebid Events documentation](https://docs.prebid.org/dev-docs/publisher-api-reference/getEvents.html)
> ADEN-13300 Send IntentIQ report on adRenderSucceeded event

- spec/ad-bidders/prebid/intent-iq/intent-iq.spec.ts
- src/ad-bidders/prebid/intent-iq/intent-iq.ts
https://fandom.atlassian.net/browse/ADEN-13291
Right now 10% of traffic that uses IntentIQ is used as a control group. It also means that 10% of traffic is not enhanced by IntentIQ and is providing worse eCPM than remaining 90%. As we want to serve more ads via IntentIQ 97% was established with IntentIQ as a compromise, so there is still enough control group data (but if it all works well we may try 99% vs 1% at some point).
> ADEN-13291 Adjust IIQ A/B groups %

- spec/ad-bidders/prebid/intent-iq/intent-iq.spec.ts
- src/ad-bidders/prebid/intent-iq/intent-iq.ts
https://fandom.atlassian.net/browse/TACO-136
Add additional targeting key value `intent_iq_ppid_group` with a copy of the same info (A/B/U) the `intent_iq_group` key-val carries
> TACO-136 IIQ Additional targeting key val

- src/ad-bidders/a9/index.ts
- src/communication/event-types.ts
- src/platforms/shared/tracking/load-times-tracker.ts
In this PR I've added an additional event that will be sent to our DWH. This way we want to track % of A9 bids that does not have consent and estimate % of events that might be invalid.
> TACO-106 - Added additional tracking event

- src/ad-bidders/prebid/adapters/ozone.ts
In this PR I've added additional config for Ozone bidder. It should use similar targeting values as our other bidders, and should use testing IDs for now.
> TACO-36 - Adjusted Ozone config

- src/core/utils/service-base-url.ts
Uses [document.currentScript](https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript) property. It will return URL of loader script that has been included in the page.
> Fix getServicesBaseURL util

- src/platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-slots-definition-repository.ts
[JIRA ➡️ ADEN-13593](https://fandom.atlassian.net/browse/ADEN-13593)
- Changed anyclip anchor point to be rendered after first header.
**Note**:
Since UCP https://github.com/Wikia/unified-platform/blob/master/skins/FandomMobile/scripts/CollapsibleSections.ts#L14 contains the following bug (in my opinion) with collapsible elements. And appends hide/show logic to the `nextSibling` instead of element inside `aria-controls` attribute we can't just add anyclip block `after` header. The workaround which I use is to add it inside content section controlled by header. As side effect hide section = video close + if areas collapsed by default, we not gonna have this ad.
Other options are:
- fix UCP collapsible behaviour, but I believe we not want to do it since it could break a lot of things there …
> ADEN-13593 Anyclip after first header

- src/ad-bidders/prebid/adapters/ozone.ts
Currently the Ozone `testgroup` is added to every ad call, even when the Ozone is disabled. This is a fix for this
> TACO-167-2 Ozone - testgroup should be added only when Ozone enabled

- @types/window/index.d.ts
- spec/platforms/shared/context/targeting/ucp-targeting.setup.spec.ts
- src/platforms/shared/context/targeting/ucp-targeting.setup.ts
- src/platforms/shared/utils/optimizely.ts
we want to pass information about the active Optimizely experiment to GAM. As the experiments sometimes are implemented in different code bases we want to have the targeting set independently to avoid introducing unnecessary communication between the adengine and the experiment code just to inform that the experiment is active.
> COTECH-713 | Add Optimizely experiments to targeting

- package.json
This script simplifies serving platforms over HTTPS using a self-signed certificate. It's a commonly used method for locally testing changes with the `adengine_version=local_https` parameter.
> Add npm script to run HTTPS dev server

- spec/ad-services/anyclip/anyclip.spec.ts
- src/ad-services/anyclip/index.ts
- src/platforms/ucp-desktop/ad-context.ts
- src/platforms/ucp-mobile/ad-context.ts
This PR updates the Anyclip configuration for both desktop and mobile UCP, allowing us to use different embed codes based on the current vertical.
The `widgetname` should be the only unique parameter. Anyclip can use that to configure various things on their side (e.g., ad schedule) without us doing anything further. No plans to make this more complex in the future. It's possible we decide at some point to add more `widgetname` options that allow configuration of yet smaller cohorts of users, but "genre" is the only solid idea we have today.
> COTECH-807 Use specific Anyclip embed codes per wiki genre

- @types/apstag/index.d.ts
- spec/ad-bidders/a9/a9.spec.ts
- spec/ad-bidders/wrappers/apstag.spec.ts
- src/ad-bidders/a9/index.ts
- src/ad-bidders/wrappers/apstag.ts
- src/communication/event-types.ts
- src/platforms/shared/modes/no-ads.mode.ts
- src/platforms/shared/setup/base-context.setup.ts
- src/platforms/shared/tracking/load-times-tracker.ts
- src/platforms/shared/tracking/tracking.setup.ts
[ADEN-13681](https://fandom.atlassian.net/browse/ADEN-13681)
[TACO-176](https://fandom.atlassian.net/browse/TACO-176)
Implements integration with Apstag `window.apstag.rpa` method. This method collects user HEM (provided by MediaWiki or LiveConnect) and provides Amazon Token that can be later on used by Apstag and A9 bidder.
This PR fixes previous problems introduced in #2163 which were caused by race condition... Before it could be a problem as well as we were not waiting for `apstag.init`, but in majority of cases it was working as expected. After some moving of code pieces the race condition was more easy to obtain.
[Fixed code diff vs previous implementation](https://github.com/Wikia/ad-engine/compare/v146.2.0...ADEN-13681-fix#diff-8e4e1901f435f31bd531736bed3ed6c16b4449e151d3330f823b99 …
> ADEN-13681 TACO-176 Create Amazon Token from HEM

- spec/core/ad-engine.spec.ts
- spec/platforms/news-and-ratings/gamespot/setup/context/slots/gamefaqs-slots-definition-repository.spec.ts
- src/communication/event-types.ts
- src/core/ad-engine.ts
- src/platforms/news-and-ratings/gamefaqs/ad-context.ts
- src/platforms/news-and-ratings/gamefaqs/gamefaqs-platform.ts
- src/platforms/news-and-ratings/gamefaqs/setup/context/slots/gamefaqs-anyclip.setup.ts
- src/platforms/news-and-ratings/gamefaqs/setup/context/slots/gamefaqs-slots-definition-repository.ts
- src/platforms/news-and-ratings/gamefaqs/styles.scss
- src/platforms/news-and-ratings/shared/setup/dynamic-slots/news-and-ratings-anyclip.setup.ts
- src/platforms/news-and-ratings/shared/setup/dynamic-slots/news-and-ratings-dynamic-slots.setup.ts
The idea is to use the same approach for anyclip as we use in FCP. So the player container is added by adengine using `slotCreatorConfig`. This way we will be less dependant on gamefaqs repo and we will be able to make changes in anyclip for gamefaqs just in adegine repo
> COTECH-765 | Anyclip updates for gamefaqs

- spec/platforms/news-and-ratings/shared/context/targeting/news-and-ratings-targeting.setup.spec.ts
- src/platforms/news-and-ratings/shared/setup/context/targeting/interfaces/targeting-params.ts
- src/platforms/news-and-ratings/shared/setup/context/targeting/news-and-ratings-targeting.setup.ts
https://fandom.atlassian.net/browse/TACO-182
On N&R sites "old" `franchise` key should be renamed to `franchise_nr` and the "old" franchise values should go there.
The new franchise values that are available in ad-tags meta tag under `franchiseRoot` key, should go to "new" `franchise` key
> TACO-182 Handle franchise key values on N&R sites

- src/platforms/news-and-ratings/comicvine/ad-context.ts
- src/platforms/news-and-ratings/shared/setup/context/base/news-and-ratings-base-context.setup.ts
In https://github.com/Wikia/ad-engine/pull/2209 I've changed the way how Anyclip services judge it's enabled or not and added similar to N&R way of calculating if it's applicable: https://github.com/Wikia/ad-engine/pull/2209/files#diff-7343fa1748a33287b2a8e4ded255b34f2943ff38233061ae882b28f0468fdf4aR126. This way whenever we want to test Connatix we block Anyclip. But the `BaseContextSetup` when I override default value of `enable` flag for Anyclip isn't used in the News&Ratings setup and thus we missed that with this change we disabled Anyclip there because it started using the default values, for example: https://github.com/Wikia/ad-engine/blob/62d593526a7b2138b9f5d12f499cd1ab9c587d94/src/platforms/news-and-ratings/comicvine/ad-context.ts#L30
It is a quick regression fix, so I didn't …
> COTECH-840 Fix Anyclip enabler on N&R

- src/platforms/shared/context/targeting/targeting-strategies/providers/common-tags.ts
https://fandom.atlassian.net/browse/COTECH-695
`canPlayVideo` method is a source of truth to determine if the FV is rendered on the page. 
See definition here: https://github.com/Wikia/unified-platform/blob/b7b9cbf018f8e4291e9afb9a0a9cc66ed262c837/extensions/fandom/ArticleVideo/src/templates/ArticleVideoController_session.php#L59-L67
> COTECH-695 | Fix hasVideoOnPage

- src/ad-bidders/prebid/index.ts
https://fandom.atlassian.net/browse/TACO-206
Ozone adds a lot of keyvals to GAM requests. See screenshot below:
We do not need most (or all) of them, so we are going to filter them out using functionality that is hidden inside of Ozone's Prebid Module: https://github.com/Wikia/Prebid.js/blob/master/modules/ozoneBidAdapter.js#L481
I have added `oz_whitelist_adserver_keys` if we would like to provide allowlist of keyvals in the future instead of filtering out all of them.
> TACO-206 Ozone should not create large set of key-vals

- @types/ads/index.d.ts
- spec/core/services/instant-config/instant-config.service.spec.ts
- spec/platforms/shared/tracking/tracking.setup.spec.ts
- spec/platforms/shared/utils/instant-config.setup.spec.ts
- src/core/services/instant-config/instant-config.service.ts
- src/platforms/bingebot/ad-context.ts
- src/platforms/f2/ad-context.ts
- src/platforms/news-and-ratings/comicvine/ad-context.ts
- src/platforms/news-and-ratings/gamefaqs/ad-context.ts
- src/platforms/news-and-ratings/gamespot/ad-context.ts
- src/platforms/news-and-ratings/giantbomb/ad-context.ts
- src/platforms/news-and-ratings/metacritic-neutron/ad-context.ts
- src/platforms/news-and-ratings/metacritic/ad-context.ts
- src/platforms/news-and-ratings/tvguide-mtc/setup/wiki-context.setup.ts
- src/platforms/news-and-ratings/tvguide/ad-context.ts
- src/platforms/shared/context/targeting/targeting-strategies/providers/common-tags.ts
- src/platforms/shared/utils/instant-config.setup.ts
- src/platforms/sports/ad-context.ts
- src/platforms/ucp-desktop/ad-context.ts
- src/platforms/ucp-mobile/ad-context.ts
- src/platforms/ucp-no-ads/setup/wiki-context.setup.ts
https://fandom.atlassian.net/browse/TACO-364
Thanks to https://github.com/Wikia/pandora/pull/17563 we now have some consistent source of truth for both AdEngine and Identity. This can be used e.g. in determining ICBM endpoint, platform name, etc..
> TACO-364 Get InstantConfigLoader params from window.ads.context

- spec/core/video/vast-parser.spec.ts
- src/ad-products/video/jwplayer/streams/jwplayer-stream-state.ts
- src/core/video/vast-parser.ts
In the new display+sync implementation we don't send VAST URL to the video player, so it can request GAM for us. We call GAM for a video by ourselves and then pass VAST XML to the player if it's not empty. This implementation however doesn't work well with the vast parser of ours which expects only VAST URL in the `vastTag` variable passed from the player. The parser tries to get from the URL the ad data including video ad "position" (if it's a pre-, mid- or post-roll) but in the new scenario it gets and returns `undefined`.
With this code changes we prioritise data from VAST URL higher but if there is no for example `vpos=preroll` in the URL we reach out to the data passed from the player with the event (`eventAdPosition`).
> COTECH-832 Fix data-vast-position for automated tests in the display+video sync scenario

- @types/window/index.d.ts
- spec/platforms/news-and-ratings/gamespot/setup/context/targeting/gamespot-targeting.setup.spec.ts
- spec/platforms/news-and-ratings/metacritic/setup/context/targeting/metacritic-targeting.setup.spec.ts
- spec/platforms/news-and-ratings/shared/context/base/news-and-ratings-base-context.setup.spec.ts
- src/platforms/news-and-ratings/gamespot/setup/context/targeting/gamespot-targeting.setup.ts
- src/platforms/news-and-ratings/metacritic/setup/context/targeting/metacritic-targeting.setup.ts
- src/platforms/news-and-ratings/shared/setup/context/base/news-and-ratings-base-context.setup.ts
- src/platforms/news-and-ratings/shared/setup/context/targeting/news-and-ratings-targeting.setup.ts
Regression tests failed to pass so reverting this to keep dev clean.
Reverts Wikia/ad-engine#2311
> Revert "ADEN-12945: switch to using GTM data to determine page s0 value"

- src/ad-bidders/prebid/id5/id5.ts
- src/ad-bidders/prebid/index.ts
- src/communication/event-types.ts
- src/platforms/shared/tracking/load-times-tracker.ts
https://fandom.atlassian.net/browse/TACO-413
The naming convention for load time events is `<partner>_started` when the partner has started, and `<partner>_loaded` when the partner is loaded.
In this PR I make ID5 and Yahoo follow this convention.
> TACO-413 Fix consistency of id5 load time events

- src/ad-services/connatix/index.ts
With the changes in this PR we stop injecting incontent video on pages with featured video for Connatix. This way there is no JS error in the console: `Cannot read properties of null (reading 'appendChild')`.
The `custom.hasIncontentPlayer` flag is being set in the AdEngine when there is no featured video: https://github.com/Wikia/ad-engine/blob/bacb10abe892e49b7fc4f5bcfbb72c999af02fa2/src/platforms/shared/context/targeting/targeting-strategies/providers/common-tags.ts#L56-L62
> COTECH-1084 Fix JS error in the console connected to incontent video

- src/ad-products/video/jwplayer/helpers/vast-tagless-request.ts
- src/core/utils/tagless-request-url-builder.ts
For e2e testing we need a way to differentiate tagless requests from regular vast requests - we did it by adding extra query parameter - `tagless=1`
> COTECH-1083 | tagless request indicator

- src/platforms/shared/setup/player.setup.ts
There are ExCo/ShowHereos/Outbrain players being loaded with JWP strategy rules which throws JS errors in the dev console. The errors are coming from the jwpManager which should only work with legacy JWP, so the changes in this PR should fix it.
> COTECH-1074 Run jwpManager.manage() only for legacy JWP

- spec/ad-bidders/prebid/id5/id5.spec.ts
- src/ad-bidders/prebid/id5/id5.ts
https://fandom.atlassian.net/browse/TACO-447
The `abTestingControlGroup` in `pbjs.getUserIds()?.id5id?.ext?.abTestingControlGroup` is the object that we take the information about whether the user is in A/B testing control group. Then we send this information to GAM with a key val.
ID5 changed their API and  `abTestingControlGroup` is available only on the first page view.
In this PR I've added saving of `abTestingControlGroup` to local storage, so it is available on every page view.
> TACO-447 Save ID5 AB testing control group to local storage
